name: Build Push Deploy

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: electronicsecommerce.azurecr.io
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3


    # -----------------------------
    # Login to Azure Container Registry
    # -----------------------------
    - name: Login to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login $ACR_LOGIN_SERVER \
        --username ${{ secrets.ACR_USERNAME }} \
        --password-stdin


    # -----------------------------
    # Build Backend Docker Image
    # -----------------------------
    - name: Build Backend
      run: |
        cd backend
        npm install
        npx prisma generate
        docker build -t $ACR_LOGIN_SERVER/$BACKEND_IMAGE:latest .


    - name: Push Backend Image
      run: |
        docker push $ACR_LOGIN_SERVER/$BACKEND_IMAGE:latest


    # -----------------------------
    # Build Frontend Docker Image
    # -----------------------------
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build
        docker build -t $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:latest .


    - name: Push Frontend Image
      run: |
        docker push $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:latest


    # -----------------------------
    # Deploy Backend VM
    # -----------------------------
    - name: Deploy Backend to VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.BACKEND_VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker login electronicsecommerce.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} \
          -p ${{ secrets.ACR_PASSWORD }}

          docker pull electronicsecommerce.azurecr.io/backend:latest

          docker stop backend || true
          docker rm backend || true

          docker run -d \
          -p 3000:3000 \
          --name backend \
          --restart unless-stopped \
          electronicsecommerce.azurecr.io/backend:latest


    # -----------------------------
    # Deploy Frontend VM
    # -----------------------------
    - name: Deploy Frontend to VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.FRONTEND_VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker login electronicsecommerce.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} \
          -p ${{ secrets.ACR_PASSWORD }}

          docker pull electronicsecommerce.azurecr.io/frontend:latest

          docker stop frontend || true
          docker rm frontend || true

          docker run -d \
          -p 80:3000 \
          --name frontend \
          --restart unless-stopped \
          electronicsecommerce.azurecr.io/frontend:latest